# .github/workflows/manual-trigger.yml
name: Manual Trigger

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Choose the type of tests to run
        options:
          - api_demo
          - ui_demo
          - demo

jobs:
  setup-api:
    uses: Srinivasaimandi/srinivasaimandi-reusable-workflows/.github/workflows/setup-express-api.yml@main

  run-tests:
    needs: setup-api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run
