name: Trigger Tests Manually
on:
    workflow_dispatch:
      inputs:
        name: 
          type: choice
          description: choose the type of tests to run
          options:
            - api_demo
            - ui_demo
            - demo
jobs:
    run-automation:
      timeout-minutes: 60
      runs-on: ubuntu-latest
        steps:
        - name: Checkout this repo
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: lts/*
        - name: Clone express-api-demo app
          run: git clone http://github.com/Srinivasaimandi/express-api-demo.git
        - name: Install and start server
          run: |
            cd express-api-demo-main
            npm install
            npm start &
            echo "api server started"
        - name: Install dependencies
          run: npm ci
        - name: Run Cypress tests
          run: npx cypress run
